# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heart_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=0)),
                ('record_id', models.IntegerField(default=0)),
                ('heart_time', models.CharField(max_length=200)),
                ('heart_date', models.CharField(max_length=200)),
                ('heart_rate', models.CharField(max_length=200)),
                ('average_rate', models.IntegerField(default=0)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='record_heart_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=200)),
                ('record_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(default='', max_length=200)),
                ('end_time', models.CharField(default='', max_length=200)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='record_shake_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=200)),
                ('record_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('shake_data', models.TextField(null=True)),
                ('shake_detail_data', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shake_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=0)),
                ('record_id', models.IntegerField(default=0)),
                ('shake_date', models.CharField(max_length=200)),
                ('shake_time', models.CharField(default='', max_length=200)),
                ('x_data', models.TextField(null=True)),
                ('y_data', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoot_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('grade_date', models.CharField(max_length=200)),
                ('grade_time', models.CharField(max_length=200)),
                ('grade_detail_time', models.CharField(default='', max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('rapid_time', models.CharField(max_length=200)),
                ('x_pos', models.CharField(max_length=200)),
                ('y_pos', models.CharField(max_length=200)),
                ('x_shake', models.FloatField(null=True)),
                ('y_shake', models.FloatField(null=True)),
                ('heart_rate', models.IntegerField(null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoot_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoot_date', models.CharField(max_length=200)),
                ('shoot_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('x_shake_data', models.TextField(null=True)),
                ('y_shake_data', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
    ]
